[package]
name = "lib_utils"
version = "0.1.0"
edition = "2021"

[dependencies]
#Standard Crates
rand = "^0.8.5"

#Non-standard Crates
dialoguer = { version = "0.11.0", features = ["completion"] }






